### ISSUE TITLE
Second delete of applet core dumps budgie-panel

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#2189]
## Description
Raised from Launchpad bug-report: https://bugs.launchpad.net/ubuntu/+source/budgie-desktop/+bug/1955891
Budgie Desktop Settings closes when clicking Delete Applet with no Applet selected

## Budgie version
10.5.3

## Operating system
Ubuntu Budgie 21.10

## Steps to reproduce the issue
-run Budgie Desktop Settings
-select a Panel
-add any applet
-select newly added applet
-delete it
-Delete/Trash button is still enabled even with no applet selected
-click on it, then 'Remove applet' makes Budgie Desktop Settings crash/close

## Actual result
budgie-panel crashes

## Expected result
no crash - suggestion is to make delete applet disabled when deleting the applet - i.e. only a focus event enables the option

## Additional information
crash file analysis
https://pastebin.com/ZTcKQ7ZV

top of the trace:

```
#0  0x00007f2ea06f70b1 in g_type_check_instance_is_fundamentally_a () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007f2ea06e5410 in g_object_get () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x0000561b7a706c20 in budgie_panel_real_remove_applet (base=0x561b7c36e410, info=0x561b7d88d040) at ../src/panel/panel.vala:708
        self = 0x561b7c36e410
        position = 0
        _tmp0_ = 0
        _tmp1_ = 0
        alignment = 0x0
        _tmp2_ = 0x0
        _tmp3_ = 0x7f2ea06dd8f0 "\363\017\036\372ATL\215%\313\321\003"
        uuid = 0x0
        _tmp4_ = 0x0
        _tmp5_ = 0x9501569061c96f00 <error: Cannot access memory at address 0x9501569061c96f00>
        notify_id = 0
        _tmp6_ = 0x7f2e80010001
        applet_parent = 0x0
        _tmp7_ = 0x7f2ea071a108
        _tmp8_ = 0x9501569061c96f00
        _tmp9_ = 0xb
        _tmp10_ = 0xffffffffffffff30
        _tmp11_ = 0xb
        _tmp12_ = 0x20842001
        _tmp13_ = 0x0
        _tmp14_ = 0x561b7eb300d8
        _tmp15_ = 0x561b7d2e0d10
        _tmp16_ = 0x0
        app_settings = 0x0
        _tmp17_ = 0x561b7eb300c0
        _tmp18_ = 0x7f2ea037ece5
        _tmp19_ = 0x0
        _tmp20_ = 0x7f2ea06dc767 "9]\bw\344H\203\304\bH\211\357[]\351\346\037\377\377f\017\037D"
        _tmp21_ = 0x561b7d2e0d00
        _tmp22_ = 0x7f2ea06dc730
        _tmp23_ = 0x561b7eac2ac0
        _tmp25_ = 0x561b7d2e0d00
        _tmp26_ = 0x7f2ea06e7bd1
        _tmp27_ = 0x561b7d2e0aa0
        _tmp28_ = 0x561b7d2e0d10
        _tmp29_ = Python Exception <class 'gdb.error'>: There is no member named keys.
0x561b7d2e0aa0
        _tmp30_ = 0x561b7d2e0d00 ""
        _tmp31_ = 0x561b7d2e0aa0 ""
        _tmp32_ = 0x284d00
        _tmp35_ = 0x7f2ea0ecff66 "H\213{XH\205\377t!\220H\211\376H\213/\350E}\315\377H\211CXH\211\357虥\377\377H\213{XH\205\377u\340H\203\304\b[]A\\A]\303\017\037D"
#3  0x00007f2ea13d6fe1 in budgie_toplevel_remove_applet (self=0x561b7c36e410, info=0x561b7d88d040) at ../src/lib/toplevel.vala:67
        _klass_ = 0x561b7c452000
        __func__ = "budgie_toplevel_remove_applet"
#4  0x0000561b7a7296d3 in budgie_applets_page_remove_applet (self=0x561b7d5a1180) at ../src/panel/settings/settings_panel_applets.vala:452
        _tmp5_ = 0x561b7c36e410
        _tmp6_ = 0x561b7d88d040
        _tmp0_ = 0x561b7d88d040
        dlg = 0x561b7d2e0d00
        _tmp1_ = 0x561b7ce5f930
        _tmp2_ = 0x561b7d2e0d00
        del = 1
        _tmp3_ = 0x561b7d2e0d00
        _tmp4_ = 0x561b7d2e0d00
        __func__ = "budgie_applets_page_remove_applet"
#5  0x0000561b7a7269f8 in _budgie_applets_page_remove_applet_gtk_button_clicked (_sender=0x561b7e320f80, self=0x561b7d5a1180)
    at ../src/panel/settings/settings_panel_applets.vala:189
```

**Comment by JoshStrobl** [comment]
Going to close this since the fix has been merged in new repo :)
