### ISSUE TITLE
Support Python Plugins

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#386]
Hi,

  I've been looking at writing some python plugins for budgie-desktop.

It seems like all budgie-desktop plugins so far are using the libpeas vala extensionbase format.  

As far as I can gather extentionbase format is for vala - Python plugins are all libpeas.activatable format e.g.

```
more /usr/lib/budgie-desktop/plugins/hello.plugin 
[Plugin]
Loader=python3
Module=hello
IAge=2
Name=Test Plugin
Description=My Test Plugin

```
source file "helloy.py":

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

gi.require_version('Budgie', '1.0')
from gi.repository import Budgie

from gi.repository import Peas
from gi.repository import GObject

#class TestPlugin(Budgie.Plugin, Peas.ExtensionBase):
class TestPlugin(GObject.Object, Peas.Activatable):
    __gtype_name = 'AltToolbarPlugin'
    object = GObject.property(type=GObject.Object)
    
    def __init__(self):
        '''
        Initialises the plugin object.
        '''
        #Budgie.Plugin.__init__(self)
        GObject.Object.__init__(self)
    
    def do_activate(self):
        print("activating sample python plugin")
        
    def get_panel_widget(self, uuid):
        return TestApplet()
        
class TestApplet(Budgie.Applet):
    def __init__(self):
        Budgie.Applet.__init(self)
        
        widget = Gtk.ToggleButton()
        img = Gtk.Image.from_icon_name("user-desktop-symbolic", Gtk.IconSize.BUTTON)
        widget.add(img)
        widget.set_tooltip_text("xyz")
        
        self.add(widget)
        self.show_all()
```

However this does not work currently because I see the following error when I do "budgie-panel --replace" and then add the plugin

`** (budgie-panel:9123): CRITICAL **: manager.vala:415: Failed to find extension for: Test Plugin
`

**Comment by ikeydoherty** [comment]
"helloy.py" ? Shouldn't that be "hello.py" ?

We don't support "do_activate", you should have "do_panel_widget()", and derive from "Budgie.Plugin"

**Comment by fossfreedom** [comment]
... ah well ... typing is not my strong suit ;)

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

gi.require_version('Budgie', '1.0')
from gi.repository import Budgie

from gi.repository import Peas
from gi.repository import GObject

class TestPlugin(Budgie.Plugin, Peas.Activatable):
    __gtype_name = 'AltToolbarPlugin'
    object = GObject.property(type=Budgie.Plugin)
    
    def __init__(self):
        '''
        Initialises the plugin object.
        '''
        Budgie.Plugin.__init__(self)
        #GObject.Object.__init__(self)
    
    #def do_activate(self):
    #    print("activating sample python plugin")
        
    def get_panel_widget(self, uuid):
        return TestApplet()
    
    #def do_get_panel_widget(self, uuid):
    #    return TestApplet()
        
class TestApplet(Budgie.Applet):
    def __init__(self):
        Budgie.Applet.__init(self)
        
        widget = Gtk.ToggleButton()
        img = Gtk.Image.from_icon_name("user-desktop-symbolic", Gtk.IconSize.BUTTON)
        widget.add(img)
        widget.set_tooltip_text("xyz")
        
        self.add(widget)
        self.show_all()

```

I get the following... any thoughts  with my class definition?

```
(budgie-panel:9322): libpeas-WARNING **: Error importing plugin 'hello':
Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/dad/.local/share/budgie-desktop/modules/hello.py", line 12, in <module>
    class TestPlugin(Budgie.Plugin, Peas.Activatable):
  File "/usr/lib/python3/dist-packages/gi/types.py", line 213, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 193, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 205, in _type_register
    _gobject.type_register(cls, namespace.get('__gtype_name__'))
TypeError: argument must be a GObject subclass

(budgie-panel:9322): libpeas-WARNING **: Error loading plugin 'hello'

** (budgie-panel:9322): CRITICAL **: manager.vala:415: Failed to find extension for: Test Plugin

```

**Comment by Quacky2200** [comment]
Looks like an initialisation of what you're creating isn't what the plugin 'loader' is asking for? I was thinking this may help? I could be wrong though?
![gobject](https://cloud.githubusercontent.com/assets/4623599/14282046/5ced84ce-fb34-11e5-9565-6308392fd1f1.PNG)

**Comment by fossfreedom** [comment]
thanks - that's the format I had at the top of the thread but Ikey wanted me to try inheriting from Budgie.Panel as per Vala plugins.

**Comment by fossfreedom** [comment]
reason why I can't use Budgie.Plugin in my class definition is because it is inherited from GLib not GObject as per the definition in https://github.com/solus-project/budgie-desktop/blob/master/plugin/budgie-1.0.vapi:

    public interface Plugin : GLib.Object {

**Comment by fossfreedom** [comment]
thanks Ikey - examples work a treat! - http://xpressubuntu.wordpress.com/2016/05/07/writing-python-applets-for-the-budgie-desktop

**Comment by ikeydoherty** [comment]
Nice :)
